### ISSUE TITLE
Worker falls with error "SQLite3::BusyException: database is locked"

### ISSUE THREAD

**Issue by juffinhalli** [sshaw/itunes_store_transporter_web#8]
Hi!
I use itunes_store_transporter_web on CentOS 6.
Unfortunately Worker regularly fall with error:

```
[Worker(host:hostname.subdomain.domain pid:11569)] 1 jobs processed at 0.0016 j/s, 0 failed ...
rake aborted!
SQLite3::BusyException: database is locked: SELECT  "delayed_jobs".* FROM "delayed_jobs"  WHERE ((run_at <= '2016-11-25 18:01:28.513696' AND (locked_at IS NULL OR locked_at < '2016-11-23 18:01:28.513700') OR locked_by = 'host:megastor.cinelab.local pid:11569') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1

Tasks: TOP => jobs:work
(See full trace by running task with --trace)
```

**Comment by sshaw** [comment]
Hi, try setting the `timeout` value in `config/itmsweb.yml`. For example: 

```yml
---
database:
  name: itmsweb
  adapter: sqlite3
  host: localhost
  username: someuser
  password: somepass
  timeout: 5000  # milliseconds 
```
